name: build
on: [pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build Example
        run: cd example/ && flutter build apk

#  build-ios:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#      - name: Build Example
#        run: cd example/ && flutter build ios